
-- Level 2

-- ID, 이름, 성별, 생년월일
    -- 생일이 3월인 여성
    -- 전화번호가 NULL인 경우는 제외
    -- 회원 ID를 기준으로 오름차순 정렬

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND DATE_OF_BIRTH LIKE "____-03-%" AND TLNO IS NOT NULL 
ORDER BY MEMBER_ID ASC

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND DATE_FORMAT(DATE_OF_BIRTH, "%m") = '03' AND TLNO IS NOT NULL 
ORDER BY MEMBER_ID ASC