
-- Level 3

-- 대장균 개체의 ID (AS ID), 자식의 수 (AS CHILD_COUNT)
    -- 자식이 없다면 자식 수 0으로 출력
    -- 개체의 ID에 대해 오름차순 정렬
    
SELECT D1.ID AS ID, COUNT(D2.ID) AS CHILD_COUNT
FROM ECOLI_DATA D1 
    LEFT JOIN ECOLI_DATA D2 ON D1.ID = D2.PARENT_ID
GROUP BY D1.ID 
ORDER BY D1.ID ASC

SELECT D1.ID, (SELECT COUNT(*) FROM ECOLI_DATA D2 WHERE D1.ID = D2.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA D1
ORDER BY D1.ID ASC