
-- Level 2

-- 대장균의 ID, 형질, 부모 대장균의 형질 
    -- 부모의 형질을 모두 보유한 대장균
    -- ID에 대해 오름차순 정렬
    
SELECT D1.ID, D1.GENOTYPE, D2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA D1 
    JOIN ECOLI_DATA D2 ON D1.PARENT_ID = D2.ID
WHERE D1.GENOTYPE & D2.GENOTYPE = D2.GENOTYPE
ORDER BY ID ASC