
-- Level 1

-- 회원의 수
    -- 2021년에 가입한 회원
    -- 나이가 20세 이상 29세 이하

SELECT COUNT(USER_ID)
FROM USER_INFO
WHERE JOINED LIKE "2021-%" AND AGE BETWEEN 20 AND 29

SELECT COUNT(USER_ID)
FROM USER_INFO
WHERE JOINED LIKE "2021-%" AND AGE >= 20 AND AGE <= 29