
-- Level 1

-- 게시글 제목, ID, 댓글 ID, 댓글 작성자, 댓글 내용, 댓글 작성일
    -- 2022년 10월에 작성된 게시글
    -- 댓글 작성일을 기준으로 오름차순, 댓글 작성일이 같다면 게시글 제목을 기준으로 오름차순
    
SELECT BOARD.TITLE, BOARD.BOARD_ID, 
        REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS,
        DATE_FORMAT(REPLY.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD, USED_GOODS_REPLY AS REPLY
WHERE BOARD.BOARD_ID = REPLY.BOARD_ID AND BOARD.CREATED_DATE LIKE "2022-10-%" 
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC