
-- Level 2

-- BASS와 SNAPPER의 수 합계

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE 
                        FROM FISH_NAME_INFO
                        WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER')

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
WHERE FISH_NAME IN ('BASS', 'SNAPPER')

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I INNER JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE 
WHERE FISH_NAME IN ('BASS', 'SNAPPER')