
-- Level 2

-- 아이템 ID, 아이템 명
    -- ROOT 아이템
    -- 아이템 ID를 기준으로 오름차순 정렬
    
SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I, ITEM_TREE T
WHERE I.ITEM_ID = T.ITEM_ID AND T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID ASC

SELECT DISTINCT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I, ITEM_TREE T
WHERE I.ITEM_ID = T.ITEM_ID AND T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID ASC