
-- Level 3

-- 아이템 ID (AS ITEM_ID), 아이템 명 (AS ITEM_NAME), 희귀도 (AS RARITY)
    -- 더이상 업그레이드할 수 없는 아이템
    -- 아이템 ID를 기준으로 내림차순 정렬
    
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY 
FROM ITEM_INFO I
WHERE NOT EXISTS (SELECT 1
                    FROM ITEM_TREE T
                    WHERE T.PARENT_ITEM_ID = I.ITEM_ID)
ORDER BY ITEM_ID DESC

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY 
FROM ITEM_INFO I
WHERE I.ITEM_ID NOT IN (SELECT T.PARENT_ITEM_ID
                        FROM ITEM_TREE T
                        WHERE T.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY 
FROM ITEM_INFO I
WHERE I.ITEM_ID NOT IN (SELECT DISTINCT T.PARENT_ITEM_ID
                        FROM ITEM_TREE T
                        WHERE T.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC