
-- Level 3

-- 회원 ID, 닉네임, 총거래금액
    -- 완료된 중고 거래의 총 금액이 70만원 이상인 사람
    -- 총거래금액을 기준으로 오름차순 정렬

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS '총거래금액'
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID AND B.STATUS = 'DONE'
GROUP BY U.USER_ID HAVING SUM(B.PRICE) >= 700000
ORDER BY 총거래금액 ASC

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS '총거래금액'
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID AND B.STATUS = 'DONE'
GROUP BY U.USER_ID HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(PRICE) ASC